# Generated by Django 4.1 on 2022-08-30 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_measurementunit_options_alter_tag_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.measurementunit', verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='amount',
            field=models.SmallIntegerField(),
        ),
    ]
