# Generated by Django 4.1 on 2022-08-30 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_following_user_subscriptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='subscriptions',
            new_name='following',
        ),
    ]
