# Generated by Django 4.1 on 2022-08-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_ingredient_measurement_unit_and_more'),
        ('users', '0004_rename_subscriptions_user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_recipes',
            field=models.ManyToManyField(blank=True, related_name='favorite_by', to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='user',
            name='shopping_cart',
            field=models.ManyToManyField(blank=True, related_name='shopping_cart', to='recipes.recipe'),
        ),
    ]
