# Generated by Django 4.1 on 2022-09-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_favorited_by_and_more'),
        ('users', '0005_user_favorite_recipes_user_shopping_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite_recipes',
        ),
        migrations.AlterField(
            model_name='user',
            name='shopping_cart',
            field=models.ManyToManyField(blank=True, related_name='shopping_cart', to='recipes.recipe', verbose_name='Список покупок'),
        ),
    ]
