# Generated by Django 4.1 on 2022-09-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_following'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='following',
            constraint=models.UniqueConstraint(fields=('subscriber', 'author'), name='not_following_yourself'),
        ),
    ]
