# Generated by Django 4.1 on 2022-09-08 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_following_not_following_yourself'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='following',
            unique_together={('subscriber', 'author')},
        ),
    ]
