# Generated by Django 4.1 on 2022-09-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_following_unique_together'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='following',
            name='not_following_yourself',
        ),
        migrations.AlterUniqueTogether(
            name='following',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='following',
            constraint=models.CheckConstraint(check=models.Q(('subscriber', models.F('author')), _negated=True), name='not_following_yourself'),
        ),
    ]
